### ISSUE TITLE
Calibrating to i.prev by default

### ISSUE THREAD

**Issue by darcyrao** [EpiModel/EpiABC#9]
I used EpiABC to calibrate my model to the prevalence of diagnosed infection (scripts [here](DWR_dissertation/Model_fits_and_simulations/scripts/burnin_WHAMP/abc/sim.prep.R)), but when I simulated using the means of the posterior distribution, I found that true prevalence (i.prev, in blue) instead of diagnosed prevalence (in red) is matching the target value. I calibrated to prevalence in years 70-79 (prevalence is still fluctuating at this point, which is related to a separate issue that I'm addressing now, but the mean true prevalence in these years is pretty closet to the target value).
<img width="800" alt="image" src="https://user-images.githubusercontent.com/15092539/55701468-1688d000-5988-11e9-84a9-a2822abb5d24.png">

I couldn't find anything in my scripts that would explain this, so on a whim, I tried defining `i.prev` in my model to be the same as diagnosed prevalence, and I defined a new variable for true prevalence. With this change, diagnosed prevalence (in red) is close(ish) my calibration target value of 0.0819 in years 70-79.
<img width="740" alt="image" src="https://user-images.githubusercontent.com/15092539/55701714-13421400-5989-11e9-8bc0-151a670c2610.png">

This suggests to me that there may be something hard-coded in the EpiABC functions to fit to "i.prev" by default.

**Comment by darcyrao** [comment]
I believe the patterns I observed simply reflect stochasticity in the simulations -- I was using merge_simfiles incorrectly so these plots only reflect data from 16 simulations. Furthermore, I have continued to have poor model fit after calibrating with EpiABC, so I think the issue is with my application of EpiABC or with the approach of selecting the mean values from the posterior distribution, rather than there being a bug in the EpiABC functions.

**Comment by smjenness** [comment]
thanks for follow-up on this @darcyrao
